### ISSUE TITLE
Cannot add a label called `location` in person card

### ISSUE THREAD

**Issue by okkhoy** [se-edu/addressbook-level4#336]
Steps to reproduce:

- Rename `address` to `location` in `java/seedu/address/ui/PersonCard.java` and `resources/view/PersonListCard.fxml`.
- Do gradle refresh (optional)
- Run the application

Throws the following exception:

```
Exception in thread "JavaFX Application Thread" java.lang.AssertionError: javafx.fxml.LoadException: 
/<path to>/addressbook-level4/bin/view/PersonListCard.fxml

	at seedu.address.ui.UiPart.<init>(UiPart.java:38)
	at seedu.address.ui.UiPart.<init>(UiPart.java:47)
	at seedu.address.ui.PersonCard.<init>(PersonCard.java:30)
	at seedu.address.ui.PersonListPanel$PersonListViewCell.updateItem(PersonListPanel.java:73)
	at seedu.address.ui.PersonListPanel$PersonListViewCell.updateItem(PersonListPanel.java:1)
	at javafx.scene.control.ListCell.updateItem(ListCell.java:471)
	at javafx.scene.control.ListCell.indexChanged(ListCell.java:330)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
	at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1957)
	at com.sun.javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1797)
	at com.sun.javafx.scene.control.skin.VirtualFlow.getCellLength(VirtualFlow.java:1879)
	at com.sun.javafx.scene.control.skin.VirtualFlow.computeViewportOffset(VirtualFlow.java:2528)
	at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1189)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)
Caused by: javafx.fxml.LoadException: 
/C:/Users/anarayan/Workspace/addressbook-level4/bin/view/PersonListCard.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at seedu.address.ui.UiPart.<init>(UiPart.java:35)
	... 33 more
Caused by: java.lang.IllegalArgumentException: Can not set javafx.scene.control.Label field seedu.address.ui.PersonCard.location to java.net.URL
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(Unknown Source)
	at java.lang.reflect.Field.set(Unknown Source)
	at javafx.fxml.FXMLLoader.injectFields(FXMLLoader.java:1163)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2554)
	... 36 more
```

**Comment by damithc** [comment]
@MightyCupcakes any idea?

**Comment by MightyCupcakes** [comment]
I am not so sure myself. I investigated it and found out the most probable cause is as such:

* All fields (defined by the @FXML annotation) in the controllers are placed in a `namespace` which is a map mapping the fx-id (string) the object itself (like a label, flowpane etc).

* In the [FXML namespace](http://hg.openjdk.java.net/openjfx/8u60/rt/file/996511a322b7/modules/fxml/src/main/java/javafx/fxml/FXMLLoader.java#l1990) there is a `LOCATION_KEY` which stores the value of String `location`

* In this [line](http://hg.openjdk.java.net/openjfx/8u60/rt/file/996511a322b7/modules/fxml/src/main/java/javafx/fxml/FXMLLoader.java#l2554), it attempts to inject a field into the controller (in this case PersonCard.java)

* This is what the [`injectFields`](http://hg.openjdk.java.net/openjfx/8u60/rt/file/996511a322b7/modules/fxml/src/main/java/javafx/fxml/FXMLLoader.java#l1157) method does: it will try to set a field with the matching key to type of the given object if it is found within the controller fields (stored in the `namespace` map mentioned earlier). It does not do anything if the field of the specified key is not found.

* Now this is where the problem starts. Since `LOCATION_KEY` is the string `location`, the `injectFields` method will try to transform the field itself (because it exists in the `namespace`) into an URL object (as defined in [this line](http://hg.openjdk.java.net/openjfx/8u60/rt/file/996511a322b7/modules/fxml/src/main/java/javafx/fxml/FXMLLoader.java#l2464)! This is of course not allowed because the location field itself defined in our controller is in fact a `Label`

**Comment by okkhoy** [comment]
@damithc @MightyCupcakes can we document this behaviour, for now? I suspect, students who want to morph it to task manager, and add location for event will hit this issue frequently.
