### ISSUE TITLE
Exception on loading tags

### ISSUE THREAD

**Issue by okkhoy** [se-edu/addressbook-level4#337]
I have the following data entered in address-book (last updated: Sem1 Ay 2016-17)

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<addressbook>
    <persons>
        <name>akshay narayan</name>
        <phone>65164779</phone>
        <email>anarayan@comp.nus.edu.sg</email>
        <address>15, Computing drive, #02-14, S117419</address>
        <tagged>official</tagged>
    </persons>
    <tags>
        <tagName>official</tagName>
    </tags>
</addressbook>
```

Updated to the latest master and launched address book app.
In the background, I get the following exception thrown:

```
seedu.address.commons.exceptions.IllegalValueException: Tags names should be alphanumeric
	at seedu.address.model.tag.Tag.<init>(Tag.java:26)
	at seedu.address.storage.XmlAdaptedTag.toModelType(XmlAdaptedTag.java:37)
	at seedu.address.storage.XmlSerializableAddressBook.lambda$1(XmlSerializableAddressBook.java:66)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at seedu.address.storage.XmlSerializableAddressBook.getTagList(XmlSerializableAddressBook.java:72)
	at seedu.address.model.AddressBook.resetData(AddressBook.java:70)
	at seedu.address.model.AddressBook.<init>(AddressBook.java:48)
	at seedu.address.model.ModelManager.<init>(ModelManager.java:37)
	at seedu.address.MainApp.initModelManager(MainApp.java:93)
	at seedu.address.MainApp.init(MainApp.java:62)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:841)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Unknown Source)
```

The way I see it, included tag is perfectly alpha-numeric. Need to find out why this exception is being thrown

**Comment by chao1995** [comment]
I guess the way we read tags from xml has been changed. Now we are using @XmlValue instead of @XmlElement. So now we don't need the <tagName> tag anymore.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<addressbook>
    <persons>
        <name>akshay narayan</name>
        <phone>65164779</phone>
        <email>anarayan@comp.nus.edu.sg</email>
        <address>15, Computing drive, #02-14, S117419</address>
        <tagged>official</tagged>
    </persons>
    <tags>official</tags>
</addressbook>
```

**Comment by damithc** [comment]
@okkhoy looks like a legacy data issue. Try deleting the data file and starting fresh.

**Comment by okkhoy** [comment]
Works well starting with a clean addressbook. 
Closing the issue
