### ISSUE TITLE
Some tests fail on Windows in headful mode

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#602]
7 tests failed in the first round and some of them still failed after a retry (screenshot below is for the retry). But all pass in headless mode.
![image](https://user-images.githubusercontent.com/1673303/28764724-93f93b34-75f9-11e7-8aa2-ca847ccff39b.png)

**Comment by damithc** [comment]
Actually, I managed to get all tests to pass after 3 retries (i.e. repeatedly running failed tests). BTW, I just right-click on the `test` folder and choose `run all tests`. On a related note, we need to add to dev guide instructions on how to run tests within Intellij.

**Comment by yamgent** [comment]
I ran these tests individually and they all pass on the first try. I will investigate this further, but I am going to give a wild guess that it is a multi-threading related problem.

**Comment by damithc** [comment]
In one case it seem to be thread related:
```

java.lang.AssertionError: javafx.fxml.LoadException: 
/C:/se-edu/addressbook-level4/build/resources/main/view/HelpWindow.fxml:7


	at seedu.address.ui.UiPart.<init>(UiPart.java:38)
	at seedu.address.ui.UiPart.<init>(UiPart.java:47)
	at seedu.address.ui.HelpWindow.<init>(HelpWindow.java:31)
	at seedu.address.ui.MainWindow.handleHelp(MainWindow.java:185)
	at seedu.address.ui.MainWindow.handleShowHelpEvent(MainWindow.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at seedu.address.commons.core.EventsCenter.post(EventsCenter.java:42)
	at seedu.address.logic.commands.HelpCommand.execute(HelpCommand.java:21)
	at seedu.address.logic.commands.HelpCommandTest.execute_help_success(HelpCommandTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: javafx.fxml.LoadException: 
/C:/se-edu/addressbook-level4/build/resources/main/view/HelpWindow.fxml:7

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at seedu.address.ui.UiPart.<init>(UiPart.java:36)
	... 48 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml.JavaFXBuilder$ObjectBuilder.build(JavaFXBuilderFactory.java:278)
	at javafx.fxml.FXMLLoader$ValueElement.processEndElement(FXMLLoader.java:763)
	at javafx.fxml.FXMLLoader.processEndElement(FXMLLoader.java:2823)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2532)
	... 51 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.JavaFXBuilder$ObjectBuilder.build(JavaFXBuilderFactory.java:270)
	... 54 more
Caused by: java.lang.IllegalStateException: Not on FX application thread; currentThread = main
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.web.WebEngine.checkThread(WebEngine.java:1243)
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:879)
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:868)
	at javafx.scene.web.WebView.<init>(WebView.java:273)
	at javafx.scene.web.WebViewBuilder.build(WebViewBuilder.java:60)
	... 63 more
```
In addition, may be there are state leaks between tests, possibly via the storage file?

**Comment by yamgent** [comment]
I digged down further and found out the reasons why they are failing:

1. Everything except HelpCommandTest and BrowserPanelTest
    1. There is a state leak between tests. The culprit is `TypicalPersons`. While it may be using `ReadOnlyPerson`, that does not guarantee that they definitely cannot be modified. In fact one can cast them to a `Person` object and modify the particulars. Hence, the modifications are leaked into the other tests, but they are generally fine when they ran individually. 
    1. **Solution:** Revert the changes where we make `TypicalPersons` from non-static to static. It must be non-static to guarantee a clean slate.
1. HelpCommandTest
    1. This test complains about that the current thread is not on JavaFX's thread. The catch: this test is not even a GUI test! I traced the problem to `EventsCenter`. Noting that `EventsCenter` is a singleton, some of the tests register their `TestApp` as an event handler, but did not unregister after the tests are over. Therefore, when `HelpCommand` raised an event, the "non-existent" `TestApp` managed to catch these events as well, and tried to handle it. Of course, that is not going to go well, so it fails as `IllegalStateException`.
    1. **Solution:** Ensure that we call `EventsCenter.clearSubscribers()` at least at the end of our GUI tests.
1. BrowserPanelTest
    1. There is a race condition. If the verification happened too soon, the BrowserPanel will not have a chance to even request for the page. If the verification happened too late, Google will morph the URL into something else (for example, from `https://www.google.com.sg/#safe=off&q=Alice+Pauline` to  `https://www.google.com.sg/search?safe=off&q=Alice+Pauline&cad=h`), so our URL is wrong.
    1. **Solution:** Verification needs to wait for a few seconds first with `GuiRobot.sleep()`. Maybe we should also use the final URL that Google morphs the original URL to?

**Comment by damithc** [comment]
Good work in troubleshooting @yamgent :+1:

**Comment by Zhiyuan-Amos** [comment]
@yamgent 

1. Can I know which test is causing the state leak of `TypicalPersons`. I agree that "one can cast them to a Person object and modify the particulars", however that should never be the case i.e. we shouldn't be doing that in both the main code base and test code base. Which is why in the first place we have a constructor in `Person` that takes in a `ReadOnlyPerson` isn't it? Driving this conclusion to its extreme, we can even argue that `ReadOnlyPerson` is actually useless since anyone can cast it to `Person` and edit it :P 

2. Is that because `AddressBookGuiTest` is clearing the subscribers in the segment of code annotated with `@Before`, not `@After`?

3. Your solution is a good workaround, though I'm not that keen on using `GuiRobot.sleep()` because we don't know how long we should `sleep()` for and it's kinda non-deterministic (what if the server lags, and BrowserPanel is stuck on retrieving the web page).

One way to do it would be to implement a new method as we discussed previously. When the page has been successfully requested, it posts an event to perform the verification immediately.

Another way to do it (I prefer this way, which is similar to the method you are suggesting except without the `GuiRobot.sleep()`) would be to update `BrowserPanel`'s  constants:
```
public static final String GOOGLE_SEARCH_URL_PREFIX = "https://www.google.com.sg/search?safe=off&q=";
public static final String GOOGLE_SEARCH_URL_SUFFIX = "&cad=h";
```

**Comment by yamgent** [comment]
> Can I know which test is causing the state leak of TypicalPersons.

Sorry I read the code wrongly, the state leak is actually happening here, whereby the array can be modified by anyone:

```
    public static final ReadOnlyPerson[] TYPICAL_PERSONS =
            new ReadOnlyPerson[]{ALICE, BENSON, CARL, DANIEL, ELLE, FIONA, GEORGE};
```

I am still in favour of making `TypicalPersons` non-static because it reduce the chance of such misuse causing unnecessary confusion. Tests should be isolated, and this issue clearly shows that the isolation is broken by making it static, allowing state leaks. The rule of thumb is don't make things harder to debug than it is.

> Is that because AddressBookGuiTest is clearing the subscribers in the segment of code annotated with `@Before`, not `@Afte`r?

Yes. I also recall that we removed several calls of `EventsCenter.clearSubscribers()` before.

> Another way to do it (I prefer this way, which is similar to the method you are suggesting except without the GuiRobot.sleep()) would be to update BrowserPanel's constants:

That does not solve the problem, because if you don't wait for it to load, it will still be at `default.html`. That is a completely different issue from morphing.

**Comment by Zhiyuan-Amos** [comment]
> Sorry I read the code wrongly, the state leak is actually happening here, whereby the array can be modified by anyone:
```
public static final ReadOnlyPerson[] TYPICAL_PERSONS =
        new ReadOnlyPerson[]{ALICE, BENSON, CARL, DANIEL, ELLE, FIONA, GEORGE};
```

Hmm how about let's make this a getter method then? We can do something like:

```
public static ReadOnlyPerson[] getTypicalPersons() {
    return new ...
}
```

That way, there isn't a state leak anymore.

> Yes. I also recall that we removed several calls of EventsCenter.clearSubscribers() before.

Ok to resolve this, we need to update `AddressBookGuiTest` as what I mentioned above. Also, tests that call `EventsCollector` need to call `clearSubscribers()` as well. But I'm not sure how to enforce this.

> That does not solve the problem, because if you don't wait for it to load, it will still be at default.html. That is a completely different issue from morphing.

Ah yes, my solution only solves the problem of late verification, not early verification. Well, then we can do:
1. When the page has been successfully requested, it posts an event to perform the verification immediately.
2. Update `BrowserPanel`'s constants i.e. Use the morphed URL.

**Comment by yamgent** [comment]
> Hmm how about let's make this a getter method then? We can do something like:

That will work yes.

> I do agree that making constants static may result in state leaks. But having to call new TypicalPersons().ALICE seems verbose too.

Up to you. In the future, you will be the one doing the debugging anyway. ;)

> Ok to resolve this, we need to update AddressBookGuiTest as what I mentioned above. Also, tests that call EventsCollector need to call clearSubscribers() as well. But I'm not sure how to enforce this.

We could start with what you have suggested. Doesn't have to be perfect, I think the higher priority here would be to get the failing tests to work first.

> Ah yes, my solution only solves the problem of late verification, not early verification. Well, then we can do:
> 
> When the page has been successfully requested, it posts an event to perform the verification immediately.
> Update BrowserPanel's constants i.e. Use the morphed URL.
> This solution solves both early verification (1) and late verification (2), and it's deterministic.

Ok. We will have to hook up the events inside `BrowserPanelHandle` or something similar, by adding a listener that detects that the page has loaded. It will be something like this (Source: https://stackoverflow.com/questions/30178238/javafx-wait-for-page-to-load-before-continuing):

```java
        webView = new WebView();
        engine = webView.getEngine();

        engine.getLoadWorker().stateProperty().addListener((obs, oldState, newState) -> {
            if (newState == Worker.State.SUCCEEDED) {
                // new page has loaded, process:
                testMethod();
            }
        });
```

**Comment by Zhiyuan-Amos** [comment]
> Up to you. In the future, you will be the one doing the debugging anyway. ;)

HAHA. @damithc what are your thoughts concerning `TypicalPersons`? Personally I think it's fine leaving it as `static`. It's similar to how we have the `StatusBarFooter`'s clock as `static` as well i.e. we should add header comments for `TypicalPersons` just as we do so for tests that test for `StatusBarFooter` when we inject the clocks.

The rest looks good man ^^.

**Comment by damithc** [comment]
> @damithc what are your thoughts concerning TypicalPersons?

Now that we have made it static, I don't mind keeping it static to give it another chance.

Test failure due to state leak happens often (note that JUnit runs test in random order, which means these problems can be very hard to debug), and even when it isn't a state leak, there is always the doubt that 'may be there is a state leak' and then we have to investigate it as one of the possibilities (which takes up extra effort). So, non-static is the more defensive approach. A bit of verbosity is a relatively cheaper price to pay.
