### ISSUE TITLE
HelpWindowTest fails on Windows

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#672]
I was running it using Intellij. Keeps failing after multiple attempts. Also fails when run using Gradle (actually 6 tests failed in that mode) but passes in headless mode. 
```

java.lang.RuntimeException: java.lang.NullPointerException

	at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:133)
	at org.testfx.api.FxRobot.interact(FxRobot.java:498)
	at seedu.address.ui.HelpWindowTest.setUp(HelpWindowTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at seedu.address.ui.testutil.StageRule$1.evaluate(StageRule.java:27)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException
	at seedu.address.ui.HelpWindow.<init>(HelpWindow.java:38)
	at seedu.address.ui.HelpWindowTest.lambda$setUp$0(HelpWindowTest.java:22)
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:364)
	at org.testfx.util.WaitForAsyncUtils.lambda$asyncFx$2(WaitForAsyncUtils.java:115)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by damithc** [comment]
Passed in my other Computer. May be dependent on resolution?

**Comment by Zhiyuan-Amos** [comment]
```
Caused by: java.lang.NullPointerException
	at seedu.address.ui.HelpWindow.<init>(HelpWindow.java:38)
```
The code at this line is: `String userGuideUrl = getClass().getResource(USERGUIDE_FILE_PATH).toString();` 

Perhaps this error may be solved by this solution that one of the students suggested at:
https://github.com/syy94/addressbook-level3/commit/496ff6495b7e6588b922ab6c3d0a2a5274e2fbed#diff-af65f0a5a3b9fe40566b4f3601da132cR43

**Comment by Zhiyuan-Amos** [comment]
On a side note, I recall that my Mac had issues starting up the application some times (it's quite hard to reproduce the bug). It crashed on `UiManager` line 79:
`return new Image(MainApp.class.getResourceAsStream(imagePath));`, as the `getResourceAsStream(imagePath)` returned null.

**Comment by pyokagan** [comment]
I guess the asciidoc files need to be built first with `gradle asciidoctor`. Usually, when running tests through gradle, gradle will automatically run `gradle asciidoctor` as a dependency, but if you run it directly via intellij I guess it bypasses gradle.

**Comment by pyokagan** [comment]
> I guess the asciidoc files need to be built first with gradle asciidoctor.

Sorry, should be `gradle processResources`

**Comment by damithc** [comment]
Thanks for the inputs @Zhiyuan-Amos @pyokagan 
If it is the asciidoc issue (it fits what I observed -- the test failure was before I pulled the gh-pages branch -- I'll confirm tonight after I go home today), I guess the easy fix is to mention it in our testing instructions.

**Comment by yamgent** [comment]
> If it is the asciidoc issue (it fits what I observed -- the test failure was before I ran gradle -- I'll confirm tonight after I go home today), I guess the easy fix is to mention it in our testing instructions.

If that is the problem, perhaps we can foolproof the loading part, so that it does not crash if the file does not exist.

```diff
diff --git a/src/main/java/seedu/address/ui/HelpWindow.java b/src/main/java/seedu/address/ui/HelpWindow.java
index c6da79fd..8e0b9e31 100644
--- a/src/main/java/seedu/address/ui/HelpWindow.java
+++ b/src/main/java/seedu/address/ui/HelpWindow.java
@@ -35,8 +35,12 @@ public class HelpWindow extends UiPart<Region> {
         dialogStage.setMaximized(true); //TODO: set a more appropriate initial size
         FxViewUtil.setStageIcon(dialogStage, ICON);

-        String userGuideUrl = getClass().getResource(USERGUIDE_FILE_PATH).toString();
-        browser.getEngine().load(userGuideUrl);
+        URL userGuideUrl = getClass().getResource(USERGUIDE_FILE_PATH);
+        if (userGuideUrl != null) {
+            browser.getEngine().load(userGuideUrl.toString());
+        } else {
+            // perhaps can consider loading an error message?
+        }
     }

     /**
```

**Comment by Zhiyuan-Amos** [comment]
Building on Wang Leng's suggestion, we can use `Gradle Tooling API` to re-run the necessary tasks to build the missing file.

```
URL userGuideUrl = getClass().getResource(USERGUIDE_FILE_PATH);
if (userGuideUrl == null) {
    GradleConnector connector = GradleConnector.newConnector();
    connector.forProjectDirectory(new File("."));
    ProjectConnection connection = connector.connect();
    BuildLauncher buildLauncher = connection.newBuild();
    buildLauncher.forTasks("processResources", "processTestResources");
    try {
        buildLauncher.run();
    } catch (GradleConnectionException gce) {
        // AssertionError?
    }
}

browser.getEngine().load(userGuideUrl.toString());
```

See https://docs.gradle.org/current/userguide/embedding.html#sec:embedding_features example 14.1 & https://dzone.com/articles/gradle-tooling-api-introduction

**Comment by damithc** [comment]
After generating the local files, the test doesn't fail at that point anymore, but fails at a different point.
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at guitests.HelpWindowTest.assertHelpWindowNotOpen(HelpWindowTest.java:56)
	at guitests.HelpWindowTest.openHelpWindow(HelpWindowTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by Zhiyuan-Amos** [comment]
> at seedu.address.ui.HelpWindowTest.setUp(HelpWindowTest.java:22)

> at guitests.HelpWindowTest.assertHelpWindowNotOpen(HelpWindowTest.java:56)

Prof you ran 2 different tests :P one is from the ui package, the other from guitests package.

**Comment by damithc** [comment]
Oops. yes :-p
`seedu.address.ui.HelpWindowTest` is passing now.

**Comment by yamgent** [comment]
> Building on Wang Leng's suggestion, we can use Gradle Tooling API to re-run the necessary tasks to build the missing file.

The user will not have Gradle installed, and the client is not expected to build the help documentation.

**Comment by Zhiyuan-Amos** [comment]
> The user will not have Gradle installed

Can import into `build.gradle`.

> the client is not expected to build the help documentation.

Yup, you are right XD wasn't thinking straight haha.

**Comment by Zhiyuan-Amos** [comment]
@damithc do you prefer to resolve this issue by producing an error message to inform developers to refer to testing instruction, or do you prefer to have the HelpWindow automatically run a build to build the missing resource file?

**Comment by damithc** [comment]
Minimally:
1. Update setting up instructions to require running `deployOfflineDocs` task
2. Show error message if offline docs are not found

Ideally:
Build offline docs if they are not present during the test.

Either way, have to do fast. :-p
