### ISSUE TITLE
Possible state leak in AddCommandSystemTest

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#675]
Windows, from Intellij: this test fails when run with other tests, but passes when run by itself. 
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at systemtests.AddressBookSystemTest.assertSelectedCardUnchanged(AddressBookSystemTest.java:177)
	at systemtests.AddCommandSystemTest.assertCommandSuccess(AddCommandSystemTest.java:229)
	at systemtests.AddCommandSystemTest.assertCommandSuccess(AddCommandSystemTest.java:217)
	at systemtests.AddCommandSystemTest.assertCommandSuccess(AddCommandSystemTest.java:200)
	at systemtests.AddCommandSystemTest.add(AddCommandSystemTest.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at systemtests.ClockRule$1.evaluate(ClockRule.java:38)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by damithc** [comment]
@Zhiyuan-Amos have a look at this one if you have time.

**Comment by pyokagan** [comment]
I guess the asciidoc files need to be built first with `gradle asciidoctor`. Usually, when running tests through gradle, gradle will automatically run `gradle asciidoctor` as a dependency, but if you run it directly via intellij I guess it bypasses gradle.

**Comment by Zhiyuan-Amos** [comment]
Seems like there are 3 `PersonListPanel`s running.

<pre>
INFO: ----------------[USER COMMAND][select 1]
Sep 18, 2017 6:31:12 PM seedu.address.commons.core.EventsCenter post
INFO: ------[Event Posted] seedu.address.commons.events.ui.JumpToListRequestEvent: <b>JumpToListRequestEvent</b>
Sep 18, 2017 6:31:12 PM seedu.address.ui.<b>PersonListPanel handleJumpToListRequestEvent</b>
INFO: ---[Event handled][JumpToListRequestEvent]
Sep 18, 2017 6:31:12 PM seedu.address.ui.<b>PersonListPanel handleJumpToListRequestEvent</b>
INFO: ---[Event handled][JumpToListRequestEvent]
Sep 18, 2017 6:31:12 PM seedu.address.ui.<b>PersonListPanel handleJumpToListRequestEvent</b>
INFO: ---[Event handled][JumpToListRequestEvent]
</pre>

**Comment by Zhiyuan-Amos** [comment]
Further updates: tests work fine after I deleted the tests in `seedu.address.ui`; the tests pass and there's no additional components as far as I can read from the logs (i.e. only 1 `PersonListPanel`) etc.

@yamgent can you take a look at the tests in the folder since they are written by you iirc :P

**Comment by yamgent** [comment]
https://github.com/se-edu/addressbook-level4/blob/66d24fc7d51db891f93095d29344300e63ce1049/src/test/java/seedu/address/ui/testutil/StageRule.java#L17 already guarantees that classes that uses `StageRule`/`UiPartRule` will clean up the GUI with `FxToolkit.cleanupStages();`. So if the problem is with `FxToolkit.cleanupStages();`, then it could be a TestFx problem, and I suggest we disable these tests first.

Otherwise, state leaks may not necessary originate from there. Do remember that test execution order may not always be the same. Just because deleting these files = no problem does not imply that the problem originated from there (which is why I always advocated techniques avoiding state leaks whenever possible - these problems can be hard to find when they crop up).

**Comment by Zhiyuan-Amos** [comment]
> Do remember that test execution order may not always be the same. Just because deleting these files = no problem does not imply that the problem originated from there

When you execute from IntelliJ, the test order is the same. Or minimally at least, I have visually observed that the tests go in order of `guitests` ->`seedu.address` -> `systemtests`. After I have removed the `seedu.address.ui`, and visually observed that the tests go in the same order, `AddCommandSystemTest` passed and there's no additional components from the logs.

**Comment by Zhiyuan-Amos** [comment]
@pyokagan can you take a look at this? This issue a bit high level.

https://github.com/se-edu/addressbook-level4/issues/675#issuecomment-330183030, https://github.com/se-edu/addressbook-level4/issues/675#issuecomment-330198268 and https://github.com/se-edu/addressbook-level4/issues/675#issuecomment-330198917

**Comment by pyokagan** [comment]
Does this solve the problem?

```diff
diff --git a/src/test/java/seedu/address/ui/GuiUnitTest.java b/src/test/java/seedu/address/ui/GuiUnitTest.java
index d163c57..f1ff065 100644
--- a/src/test/java/seedu/address/ui/GuiUnitTest.java
+++ b/src/test/java/seedu/address/ui/GuiUnitTest.java
@@ -2,11 +2,13 @@ package seedu.address.ui;
 
 import java.util.Optional;
 
+import org.junit.After;
 import org.junit.Rule;
 
 import guitests.GuiRobot;
 import guitests.guihandles.exceptions.NodeNotFoundException;
 import javafx.scene.Node;
+import seedu.address.commons.core.EventsCenter;
 import seedu.address.ui.testutil.UiPartRule;
 
 /**
@@ -18,6 +20,11 @@ public abstract class GuiUnitTest {
 
     protected final GuiRobot guiRobot = new GuiRobot();
 
+    @After
+    public void tearDown() {
+        EventsCenter.clearSubscribers();
+    }
+
     /**
      * Retrieves the {@code query} node owned by the {@code rootNode}.
      *
```

If yes, this just increases my dislike for our global EventsCenter even more >:( >:( Its too easy to cause state leaks.

**Comment by Zhiyuan-Amos** [comment]
Yup passes on my side.

**Comment by pyokagan** [comment]
Great if true, but I also couldn't reproduce the problem with gradle, even after I set `forkEvery` to a super high number. Not sure what gradle is doing differently here.

**Comment by damithc** [comment]
Works for me too, on the set up that used to fail earlier 💯

**Comment by Zhiyuan-Amos** [comment]
Teach me to be as pro as you pls senpai @pyokagan. Can you do a PR for it since it's all your work ^^

**Comment by damithc** [comment]
> Teach me to be as pro as you pls senpai @pyokagan. Can you do a PR for it since it's all your work ^^

He did the hard part. Let's do the rest ourselves :-) You can credit him in the commit message.
