### ISSUE TITLE
guitests.HelpWindowTest.openHelpWindow failing on Windows

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#680]
Failing in one of my Comps, even after multiple tries. This was failing y'day too. I thought the two failures are related and reported only one of them (#672). 
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at guitests.HelpWindowTest.assertHelpWindowNotOpen(HelpWindowTest.java:56)
	at guitests.HelpWindowTest.openHelpWindow(HelpWindowTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by damithc** [comment]
Yes. I suspect the step where the focus is supposed to shift to the Browser window is not happening. That's probably why `F1` key triggers the help window when it is not supposed to, hence causing the test failure.

**Comment by damithc** [comment]
When I observe how the test runs, it looks like the testFx clicks on the bar dividing the person panel and browser panel, instead of clicking on the browser panel. I tried changing display resolution but didn't seem to help.

**Comment by Zhiyuan-Amos** [comment]
On my side, TestFx clicks on the center of each component (i.e. for the browser panel, it clicks on the center of the rectangle that's containing the browser panel). I tried playing around with the screen size (`TestApp` line 69), and it's still clicking on the center of each component.

Can I check if the other components are clicked at the center of their respective containers?

**Comment by damithc** [comment]
It doesn't seem to be clicking in the middle.
![helpwindowtest](https://user-images.githubusercontent.com/1673303/30570248-9eb24558-9d12-11e7-8ddd-3359688f4662.gif)

**Comment by Zhiyuan-Amos** [comment]
@yamgent I can't think of any idea why this is happening, since we configured the clicks to happen on the root nodes of each component right? :0

**Comment by Zhiyuan-Amos** [comment]
Prof, can I know which software did you use to take the video of the test? ><

**Comment by damithc** [comment]
> Prof, can I know which software did you use to take the video of the test? ><

I used GifRecorder. First time using it myself. Just downloaded it after a quick Google search. Not sure if it the best option :-)
