### ISSUE TITLE
Random NPEs in javafx.web/com.sun.javafx.webkit.prism.WCFontImpl.getFont when running tests

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#882]
We've been having this for quite a while but it happens extremely rarely.

Factors:

* headless mode
* Load a web page with custom fonts

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at javafx.web/com.sun.javafx.webkit.prism.WCFontImpl.getFont(WCFontImpl.java:54)
        at javafx.web/com.sun.javafx.webkit.prism.PrismGraphicsManager.getWCFont(PrismGraphicsManager.java:84)
        at javafx.web/com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
        at javafx.web/com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:868)
        at javafx.web/com.sun.webkit.network.URLLoader.lambda$didFinishLoading$5(URLLoader.java:859)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
        at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
        at java.base/java.lang.Thread.run(Thread.java:844)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at javafx.web/com.sun.javafx.webkit.prism.WCFontImpl.getFont(WCFontImpl.java:54)
        at javafx.web/com.sun.javafx.webkit.prism.PrismGraphicsManager.getWCFont(PrismGraphicsManager.java:84)
        at javafx.web/com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
        at javafx.web/com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:868)
        at javafx.web/com.sun.webkit.network.URLLoader.lambda$didFinishLoading$5(URLLoader.java:859)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
        at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
        at java.base/java.lang.Thread.run(Thread.java:844)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at javafx.web/com.sun.javafx.webkit.prism.WCFontImpl.getFont(WCFontImpl.java:54)
        at javafx.web/com.sun.javafx.webkit.prism.PrismGraphicsManager.getWCFont(PrismGraphicsManager.java:84)
        at javafx.web/com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
        at javafx.web/com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:868)
        at javafx.web/com.sun.webkit.network.URLLoader.lambda$didFinishLoading$5(URLLoader.java:859)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
        at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
        at java.base/java.lang.Thread.run(Thread.java:844)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at javafx.web/com.sun.javafx.webkit.prism.WCFontImpl.getFont(WCFontImpl.java:54)
        at javafx.web/com.sun.javafx.webkit.prism.PrismGraphicsManager.getWCFont(PrismGraphicsManager.java:84)
        at javafx.web/com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
        at javafx.web/com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:868)
        at javafx.web/com.sun.webkit.network.URLLoader.lambda$didFinishLoading$5(URLLoader.java:859)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
        at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
        at java.base/java.lang.Thread.run(Thread.java:844)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at javafx.web/com.sun.javafx.webkit.prism.WCFontImpl.getFont(WCFontImpl.java:54)
#
        at javafx.web/com.sun.javafx.webkit.prism.PrismGraphicsManager.getWCFont(PrismGraphicsManager.java:84)
        at javafx.web/com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
        at javafx.web/com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:868)
        at javafx.web/com.sun.webkit.network.URLLoader.lambda$didFinishLoading$5(URLLoader.java:859)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
        at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
        at java.base/java.lang.Thread.run(Thread.java:844)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at javafx.web/com.sun.javafx.webkit.prism.WCFontImpl.getFont(WCFontImpl.java:54)
        at javafx.web/com.sun.javafx.webkit.prism.PrismGraphicsManager.getWCFont(PrismGraphicsManager.java:84)
        at javafx.web/com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
        at javafx.web/com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:868)
        at javafx.web/com.sun.webkit.network.URLLoader.lambda$didFinishLoading$5(URLLoader.java:859)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa6a111320d, pid=20700, tid=20748
#
# JRE version: Java(TM) SE Runtime Environment (9.0+11) (build 9.0.4+11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (9.0.4+11, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libjfxwebkit.so+0x123320d]  WebCore::FontCache::lastResortFallbackFont(WebCore::FontDescription const&)+0x4d
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/pyokagan/pyk/addressbook-level4/hs_err_pid20700.log
        at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
        at java.base/java.lang.Thread.run(Thread.java:844)
Compiled method (c1)    3207 3824       3       java.nio.ByteBuffer::clear (7 bytes)
 total in heap  [0x00007fa75a968a90,0x00007fa75a968e80] = 1008
 relocation     [0x00007fa75a968c00,0x00007fa75a968c30] = 48
 main code      [0x00007fa75a968c40,0x00007fa75a968d80] = 320
 stub code      [0x00007fa75a968d80,0x00007fa75a968e10] = 144
 metadata       [0x00007fa75a968e10,0x00007fa75a968e20] = 16
 scopes data    [0x00007fa75a968e20,0x00007fa75a968e38] = 24
 scopes pcs     [0x00007fa75a968e38,0x00007fa75a968e78] = 64
 dependencies   [0x00007fa75a968e78,0x00007fa75a968e80] = 8
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

More info:
```
---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x00007fa77489b800 JavaThread "Thread-0" [_thread_in_native, id=20777, stack(0x00007fa65c084000,0x00007fa65c185000)]
  0x00007fa6b024a000 JavaThread "URL-Loader-7" daemon [_thread_blocked, id=20761, stack(0x00007fa65e0fd000,0x00007fa65e1fe000)]
  0x00007fa6b0248000 JavaThread "URL-Loader-6" daemon [_thread_blocked, id=20760, stack(0x00007fa65e1fe000,0x00007fa65e2ff000)]
  0x00007fa6b0246000 JavaThread "URL-Loader-5" daemon [_thread_blocked, id=20759, stack(0x00007fa65e2ff000,0x00007fa65e400000)]
  0x00007fa6b0244000 JavaThread "URL-Loader-4" daemon [_thread_blocked, id=20758, stack(0x00007fa6a806a000,0x00007fa6a816b000)]
  0x00007fa6b0242800 JavaThread "URL-Loader-3" daemon [_thread_blocked, id=20757, stack(0x00007fa6a94ff000,0x00007fa6a9600000)]
  0x00007fa6b0240800 JavaThread "URL-Loader-2" daemon [_thread_blocked, id=20756, stack(0x00007fa6a98ff000,0x00007fa6a9a00000)]
  0x00007fa6b0224800 JavaThread "URL-Loader-1" daemon [_thread_blocked, id=20755, stack(0x00007fa6aa482000,0x00007fa6aa583000)]
  0x00007fa6b01c7000 JavaThread "Disposer" daemon [_thread_blocked, id=20754, stack(0x00007fa6cc0ff000,0x00007fa6cc200000)]
  0x00007fa6b01a8800 JavaThread "Prism Font Disposer" daemon [_thread_blocked, id=20752, stack(0x00007fa6cc4a7000,0x00007fa6cc5a8000)]
  0x00007fa6b00e7800 JavaThread "Java2D Disposer" daemon [_thread_blocked, id=20751, stack(0x00007fa6cc81f000,0x00007fa6cc920000)]
  0x00007fa6b0012000 JavaThread "Timer-0" daemon [_thread_blocked, id=20749, stack(0x00007fa6ce361000,0x00007fa6ce462000)]
=>0x00007fa6b8045000 JavaThread "JavaFX Application Thread" daemon [_thread_in_native, id=20748, stack(0x00007fa6ce662000,0x00007fa6ce763000)]
  0x00007fa6b4011000 JavaThread "JavaFX-Launcher" daemon [_thread_blocked, id=20746, stack(0x00007fa6cf3fc000,0x00007fa6cf4fd000)]
  0x00007fa6c413d000 JavaThread "testfx-async-pool-thread-1" daemon [_thread_blocked, id=20745, stack(0x00007fa6ced00000,0x00007fa6cee01000)]
  0x00007fa7742b2800 JavaThread "Service Thread" daemon [_thread_blocked, id=20733, stack(0x00007fa6fc129000,0x00007fa6fc22a000)]
  0x00007fa77425e000 JavaThread "Common-Cleaner" daemon [_thread_blocked, id=20732, stack(0x00007fa6fc22a000,0x00007fa6fc32b000)]
  0x00007fa77423f000 JavaThread "Sweeper thread" daemon [_thread_blocked, id=20731, stack(0x00007fa6fc753000,0x00007fa6fc854000)]
  0x00007fa77423d000 JavaThread "C1 CompilerThread3" daemon [_thread_blocked, id=20730, stack(0x00007fa6fc854000,0x00007fa6fc955000)]
  0x00007fa77423b000 JavaThread "C2 CompilerThread2" daemon [_thread_in_native, id=20729, stack(0x00007fa6fc955000,0x00007fa6fca56000)]
  0x00007fa774239000 JavaThread "C2 CompilerThread1" daemon [_thread_in_native, id=20728, stack(0x00007fa6fca56000,0x00007fa6fcb57000)]
  0x00007fa774235000 JavaThread "C2 CompilerThread0" daemon [_thread_in_native, id=20727, stack(0x00007fa6fcb57000,0x00007fa6fcc58000)]
  0x00007fa774237000 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=20726, stack(0x00007fa6fcc58000,0x00007fa6fcd59000)]
  0x00007fa77421a000 JavaThread "Finalizer" daemon [_thread_blocked, id=20725, stack(0x00007fa6fcef6000,0x00007fa6fcff7000)]
  0x00007fa774212000 JavaThread "Reference Handler" daemon [_thread_blocked, id=20724, stack(0x00007fa6fcff7000,0x00007fa6fd0f8000)]
  0x00007fa774015000 JavaThread "main" [_thread_blocked, id=20702, stack(0x00007fa77dd4a000,0x00007fa77de49000)]

Other Threads:
  0x00007fa774208000 VMThread "VM Thread" [stack: 0x00007fa6fd0fa000,0x00007fa6fd1fa000] [id=20723]
  0x00007fa7744a7000 WatcherThread [stack: 0x00007fa6fc029000,0x00007fa6fc129000] [id=20734]
  0x00007fa77402d000 GCTaskThread "GC Thread#0" [stack: 0x00007fa77a1a3000,0x00007fa77a2a3000] [id=20703]
  0x00007fa77402e800 GCTaskThread "GC Thread#1" [stack: 0x00007fa77a0a1000,0x00007fa77a1a1000] [id=20704]
  0x00007fa774030000 GCTaskThread "GC Thread#2" [stack: 0x00007fa779f9f000,0x00007fa77a09f000] [id=20705]
  0x00007fa774032000 GCTaskThread "GC Thread#3" [stack: 0x00007fa779e9d000,0x00007fa779f9d000] [id=20706]
  0x00007fa774033800 GCTaskThread "GC Thread#4" [stack: 0x00007fa779d9b000,0x00007fa779e9b000] [id=20707]
  0x00007fa774035800 GCTaskThread "GC Thread#5" [stack: 0x00007fa779c99000,0x00007fa779d99000] [id=20708]
  0x00007fa774037000 GCTaskThread "GC Thread#6" [stack: 0x00007fa779b97000,0x00007fa779c97000] [id=20709]
  0x00007fa774039000 GCTaskThread "GC Thread#7" [stack: 0x00007fa779a95000,0x00007fa779b95000] [id=20710]
  0x00007fa774090000 ConcurrentGCThread "G1 Main Marker" [stack: 0x00007fa7582ca000,0x00007fa7583ca000] [id=20720]
  0x00007fa774091800 ConcurrentGCThread "G1 Marker#0" [stack: 0x00007fa7581c8000,0x00007fa7582c8000] [id=20721]
  0x00007fa774093800 ConcurrentGCThread "G1 Marker#1" [stack: 0x00007fa7580c6000,0x00007fa7581c6000] [id=20722]
  0x00007fa774047800 ConcurrentGCThread "G1 Refine#0" [stack: 0x00007fa778a7d000,0x00007fa778b7d000] [id=20718]
  0x00007fa774045800 ConcurrentGCThread "G1 Refine#1" [stack: 0x00007fa778b7f000,0x00007fa778c7f000] [id=20717]
  0x00007fa774044000 ConcurrentGCThread "G1 Refine#2" [stack: 0x00007fa778c81000,0x00007fa778d81000] [id=20716]
  0x00007fa774042000 ConcurrentGCThread "G1 Refine#3" [stack: 0x00007fa778d83000,0x00007fa778e83000] [id=20715]
  0x00007fa774040800 ConcurrentGCThread "G1 Refine#4" [stack: 0x00007fa778e85000,0x00007fa778f85000] [id=20714]
  0x00007fa77403e800 ConcurrentGCThread "G1 Refine#5" [stack: 0x00007fa778f87000,0x00007fa779087000] [id=20713]
  0x00007fa77403c800 ConcurrentGCThread "G1 Refine#6" [stack: 0x00007fa779089000,0x00007fa779189000] [id=20712]
  0x00007fa77403b000 ConcurrentGCThread "G1 Refine#7" [stack: 0x00007fa77918b000,0x00007fa77928b000] [id=20711]
  0x00007fa774049000 ConcurrentGCThread "G1 Young RemSet Sampling" [stack: 0x00007fa77897b000,0x00007fa778a7b000] [id=20719]
```

**Comment by pyokagan** [comment]
I'm closing this because I actually believe this bug will *very likely* not happen any more.

It's been a long time since I've investigated this, but if I recall correctly this occurs when there is a race condition between the WebView load callback (when the webpage finishes loading), and the termination of the prism engine. In other words, the application terminates *before* the WebView finishes loading.

This used to happen often because `forkEvery` used to be set to `1` in our `build.gradle` file, which has the effect of terminating the test runner after running every test class, which thus makes it more likely for this bug to happen.

Since https://github.com/se-edu/addressbook-level4/commit/c205d6f7dd9c7aef0287fafd311092d3609702ab that has been removed, which makes it extremely difficult for this race condition to occur. Accordingly, reports of this bug has been disappeared.
